# Startup Programs
exec-once = systemctl --user start hyprland-session.target
exec-once = awww-daemon
exec-once = wal -R
# exec-once = waybar
# exec-once = systemctl --user start hyprpolkitagent
exec-once = fcitx5
exec-once = easyeffects
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
# exec-once = hyprsunset

# Programs
$terminal = kitty
$fileManager = thunar
$menu = hyprlauncher
$browser = zen-browser
#$launcher = ~/.config/rofi/launchers/type-2/launcher.sh
$launcher = rofi -show drun -theme $HOME/git-related/theme.rasi
$clipboard = rofi -show dmenu -theme /home/rui/git-related/theme.rasi
$notification = swaync-client -t
$lock = hyprlock
$spotify = DRI_PRIME=1 spotify-launcher
